<div id="authAddForm">
    <p id="authTypeSelect">
        <label for="authType">Authorization Type:</label>
        <select name="authType" id="authentication-select">
            <option value=""></option>
            <option value="basic">Basic</option>
            <option value="token">Token</option>
        </select>
        <div id="authentication-details">
            <p id="basic-auth" class="auth-input">
                <label for="basic-username">Username : Password/API Key</label>
                <input type="text" name="basic-username" /> : <input type="text" name="basic-password" />
            </p>
            <p id="token-auth" class="auth-input">
                <label for="token">Token: </label>
                <input type="text" name="token" />
            </p>
        </div>
    </p>
</div>

<script type="text/javascript">
    jQuery(function ($) {
        $('#authentication-select').change( function () {
            $('.auth-input').css('display', 'none');

            let field = '';

            switch ($(this).val()) {
                case 'basic':
                    field = 'basic-auth';
                    break;
                case 'token':
                    field = 'token-auth';
                    break;
            }

            $('#' + field).css('display', 'block');
        });
    });
</script>