<h1 class="wp-heading-inline">Add Service</h1>
<div id="add-service-box" class="postbox">
    <form method="post" id="add-service" action="<?= esc_url(admin_url('admin-post.php')) ?>"
          enctype="multipart/form-data">
        <p>
            <label for="serviceName">Service Name: </label>
            <input type="text" name="serviceName"
                   value="<?php if (isset($data->service_name)) echo $data->service_name; ?>">
        </p>
        <p>
            <label for="serviceURL">Service URL: </label>
            <input type="text" name="serviceURL" value="<?php if (isset($data->service_url)) echo $data->cron_run; ?>">
        </p>
        <p id="keyCheckField">
            <label for="keyCheck">Send Authorization Key?: </label>
            <input type="checkbox" name="keyCheck" id="keyCheck" value="on">
        </p>
        <p>
            <label for="dataFormat">Data Format</label>
            <select name="dataFormat">
                <option value=""></option>
                <option value="xml">XML</option>
                <option value="csv">CSV</option>
                <option value="json">JSON</option>
            </select>
        </p>
        <p>
            <input type="button" class="button button-primary" value="Test Connection" id="test-connection">
        </p>
        <input type="hidden" name="action" value="test_connection">
        <?= wp_nonce_field('test-connection'); ?>
        <!--
            <li>
                <label for="cronSchedule">Call Every: </label>
                <select name="cronSchedule" required="">
                    <option value="" <?php if (isset($data->cron_run) && $data->cron_run == "") echo 'selected="selected"'; ?> />
                    <option value="0" <?php if (isset($data->cron_run) && $data->cron_run == 1) echo 'selected="selected"'; ?> >Only Once</option>
                    <option value="1" <?php if (isset($data->cron_run) && $data->cron_run == 5) echo 'selected="selected"'; ?> >Every 5 Minutes</option>
                    <option value="2" <?php if (isset($data->cron_run) && $data->cron_run == 15) echo 'selected="selected"'; ?> >Every 15 Minutes</option>
                    <option value="3" <?php if (isset($data->cron_run) && $data->cron_run == 30) echo 'selected="selected"'; ?> >Every 30 Minutes</option>
                    <option value="4" <?php if (isset($data->cron_run) && $data->cron_run == 60) echo 'selected="selected"'; ?> >Every Hour</option>
                    <option value="5" <?php if (isset($data->cron_run) && $data->cron_run == 180) echo 'selected="selected"'; ?> >Every Three Hours</option>
                    <option value="6" <?php if (isset($data->cron_run) && $data->cron_run == 1440) echo 'selected="selected"'; ?> >Once a Day</option>
                    <option value="7" <?php if (isset($data->cron_run) && $data->cron_run == 10080) echo 'selected="selected"'; ?> >Once a Week</option
                    <option value="8" <?php if (isset($data->cron_run) && $data->cron_run == 43800) echo 'selected="selected"'; ?> >Once a Month</option>
                </select>
            </li>
            -->
        <!--
            <li>
                <input class="button button-primary" type="submit" value="Submit" name="submit">
                <input type="hidden" name="action" value="form_submit">
                <input type="hidden" name="controllerAction" value="addService">
                <?= wp_nonce_field('form-controller'); ?>
                <?php if (isset($_GET['id'])) {
            echo '<input type="hidden" name=serviceId value="' . $_GET['id'] . '">';
        } ?>
            </li>
            -->
        <div class="loader-overlay">
            <div class="loader-overlay-content">
                <p class="loader-message">Loading...</p>
               <span class="loader"></span>
            </div>
        </div>
    </form>
</div>