<?php
/** @var $this \ExternalServices\Classes\Utilities\View_Controller */
/** @var $block \ExternalServices\Classes\Blocks\Add_Service_Block */
$block = $this->getBlockClass();
?>

<h1 class="wp-heading-inline">Add Service</h1>
<p>Export:
    https://export.complies.nl/getproducts?format=csv&key=d0a53c8278749ef662d507b763f7eb2e2aa3985a22a7475f06b80e56b6add567</p>
<p>API: https://api.complies.nl/0/getproducts (75c42e4b12ded69bcec79ae8a7a53e34d9de06b341575ada568b45ec5b76c8b4)</p>
<div id="add-service-box" class="postbox">
    <form method="post" id="add-service" action="<?= esc_url( admin_url( 'admin-post.php' ) ) ?>?action=<?= $block->getPageKey() ?>_submit"
          enctype="multipart/form-data">
        <p>
            <label for="serviceName">Service Name: </label>
            <input type="text" name="serviceName"
                   value="<?php if ( isset( $data->service_name ) ) {
				       echo $data->service_name;
			       } ?>">
        </p>
        <p>
            <label for="serviceUrl">Service URL: </label>
            <input type="text" name="serviceUrl" value="<?php if ( isset( $data->service_url ) ) {
				echo $data->cron_run;
			} ?>">
        </p>
        <p id="authHeadField">
            <label for="keyCheck">Add Custom Authentication? (Advanced): </label>
            <input type="checkbox" name="authHeadCheck" id="auth-header"
        </p>
        <div id="authAddForm" style="display: <?= $block->getAuthorizationSettingsDisplayStatus() ?>">
            <p id="authTypeSelect">
                <label for="authType">Authorization Type:</label>
                <select name="authType" id="authentication-select">
                    <option value=""></option>
                    <option value="basic">Basic</option>
                    <option value="token">Token</option>
                </select>
            <div id="authentication-details">
                <p id="basic-auth" class="auth-input">
                    <label for="basic-username">Username : Password/API Key</label>
                    <input type="text" name="basic-username"/> : <input type="text" name="basic-password"/>
                </p>
                <p id="token-auth" class="auth-input">
                    <label for="token">Token: </label>
                    <input type="text" name="api-token"/>
                </p>
            </div>
        </div>
        <p id="dataFormatField">
            <label for="dataFormat">Data Format</label>
            <select name="dataFormat" id="data-format">
                <option value=""></option>
                <option value="xml">XML</option>
                <option value="csv">CSV</option>
                <option value="json">JSON</option>
            </select>
        </p>
        <div id="csvParseForm" style="display: <?= $block->getCsvSettingsDisplayStatus() ?>">
            <p>
                <label for="csv-delimeter">Deliminate rows by</label>
                <input type="text" name="csv-delimeter" placeholder="Optional, defaults to ','"/>
            </p>
            <p>
                <label for="csv-enclosure">Enclose rows character</label>
                <input type="text" name="csv-enclosure" placeholder="Optional, defaults to nothing"/>
            </p>
            <p>
                <label for="csv-escape">Escape Character</label>
                <input type="text" name="csv-escape" placeholder="Optional, defaults to '\\'"/>
            </p>
            <p>
                <label for="csv-columncount">Column Count</label>
                <input type="text" name="csv-columncount"/>
                <span class="input-notice">Please specify a number to assist with mapping of each data column to a record. Defaults to 1.</span>
            </p>
            <p>
                <label for="csv-end-escape">Escape new line at the end of each record?</label>
                <input type="checkbox" name="csv-end-escape" value="1"/>
                <span class="input-notice">With some CSV's, a new line is populated at the end of each row of the CSV to indicate that it's the end of a data entity. Checking this will correctly map each data column to the correct entity.</span>
            </p>
        </div>
        <p>
            <input type="submit" class="button button-primary" value="Test Connection" id="test-connection">
        </p>
		<?= wp_nonce_field( $block->getPageKey() ); ?>
        <!--
            <li>
                <input class="button button-primary" type="submit" value="Submit" name="submit">
                <input type="hidden" name="action" value="form_submit">
                <input type="hidden" name="controllerAction" value="addService">
                <?= wp_nonce_field( 'form-controller' ); ?>
                <?php if ( isset( $_GET['id'] ) ) {
			echo '<input type="hidden" name=serviceId value="' . $_GET['id'] . '">';
		} ?>
            </li>
            -->
		<?= $block->getLoaderHtml() ?>
    </form>
</div>

<script type="text/javascript" src="<?= EXTERNAL_SERVICES_JS . 'viewObjects/es-add-service.js' ?>"></script>
<script type="text/javascript">
    jQuery(function ($) {
        let addService = new EsAddService();

        // Show/remove advanced authorization fields
        $('#auth-header').change(function () {
            addService.displayOrRemoveAuthorizationSettingsFields($(this));
        });

        // data format dropdown event
        $('#data-format').change(function () {
            addService.displayOrRemoveCsvSettingsFields($(this));
        });

        // check whether form is valid
        $('#add-service').one('submit', function (event) {
            addService.checkIfFormIsValid(event, $(this), '<?= $block->getPageKey() ?>');
        });

        $('#authentication-select').change( function () {
            addService.showBasicOrTokenAuthFields($(this));
        });
    });
</script>