<div id="authAddForm">
    <p id="authTypeSelect">
        <label for="authType">Authorization Type:</label>
        <select name="authType" id="authentication-select">
            <option value=""></option>
            <option value="basic">Basic</option>
            <option value="oauth1">Outh 1.0</option>
            <option value="oauth2">Outh 2.0</option>
        </select>
        <div id="authentication-details">
            <p id="basic-auth" class="auth-input">
                <label for="basic-username">Username : API Key</label>
                <input type="text" name="basic-username" /> : <input type="text" name="basic-apiKey" />
            </p>
            <p id="oauth-1" class="auth-input">
                <label for="oauth-1-token">Token: </label>
                <input type="text" name="oauth-1-token" />
            </p>
            <p id="oauth-2" class="auth-input">
                <label for="oauth-2-token">Token: </label>
                <input type="text" name="oauth-1-token" />
            </p>
        </div>
    </p>
</div>

<script type="text/javascript">
    jQuery(function ($) {
        $('#authentication-select').change( function () {
            $('.auth-input').css('display', 'none');

            let field = '';

            switch ($(this).val()) {
                case 'basic':
                    field = 'basic-auth';
                    break;
                case 'oauth1':
                    field = 'oauth-1';
                    break;
                case 'oauth2':
                    field = 'oauth-2';
                    break;
            }

            $('#' + field).css('display', 'block');
        });
    });
</script>