<?php
/** @var $this \ExternalServices\Classes\Utilities\View_Controller */
/** @var $block \ExternalServices\Classes\Blocks\Configure_Service_Block */
$block = $this->getBlockClass();
$data  = $block->getFirstIndexOfConnectionData();
?>

<h1 class="wp-heading-inline">Configure Service</h1>
<div class="postbox" id="configure-service-section">
	<?php if ( $data == null ): ?>
        <p>No results gathered from the connection. Please try another URL or changing settings.</p>
	<?php else: ?>
        <p>
            The following data keys are found from the connection. Please select which keys you wish to map:
        </p>
        <form method="post" id="configure-service" action="<?= esc_url( admin_url( 'admin-post.php' ) ) ?>?action=<?= $block->getPageKey() ?>_submit"
              enctype="multipart/form-data">
            <table>
                <tbody>
                <tr class="select-all">
                    <td>
                        <input type="checkbox" name="all" value="all" id="all-keys"/>
                        <label for="all">Select All</label>
                    </td>
                </tr>
				<?php foreach ( $data as $key => $value ): ?>
                    <tr>
                        <td>
                            <input class="data-mappings" type="checkbox" id="<?= $key ?>"
                                   name="<?= $key ?>-service-field"/>
                            <label for="<?= $key ?>"><?= $block->formatDataKey( $key ) ?></label>
                            <p class="sample-data"> - <?= ( empty( $value ) ) ? '(Empty)' : $value; ?></p>
                        </td>
                    </tr>
                    <tr class="data-map-settings <?= $key ?>" style="display: none">
                        <td>
                            <div class="postbox">
                                <table>
                                    <tr class="field-map-row">
                                        <td>
                                            <p>Map as: </p>
                                        </td>
                                        <td>
                                            <select name="<?= $key ?>-fieldMap" class="field-map-select">
                                                <option value=""></option>
                                                <option value="title">Title</option>
                                                <option value="description">Description</option>
                                                <option value="short_description">Short Description</option>
                                                <option value="category">Category</option>
                                                <option value="main_image">Main Image</option>
                                                <option value="gallery_image">Gallery Image</option>
                                                <option value="sku">SKU</option>
                                                <option value="tag">Tag</option>
                                                <option value="custom_attribute">Custom Attribute</option>
                                            </select>
                                        </td>
                                    </tr>
                                    <tr class="product-category">
                                        <td>
                                            <p>Category</p>
                                        </td>
                                        <td>
                                            <select name="<?= $key ?>-productCategory" multiple>
												<?php foreach ( $block->getProductCategoryArray() as $category ): ?>
                                                    <option value="<?= $category->slug ?>"><?= $category->name ?></option>
												<?php endforeach; ?>
                                            </select>
                                        </td>
                                    </tr>
                                    <tr class="product-tags">
                                        <td>
                                            <p>Tags</p>
                                        </td>
                                        <td>
                                            <select name="<?= $key ?>-productTags" multiple>
												<?php foreach ( $block->getProductTagsArray() as $tag ): ?>
                                                    <option value="<?= $tag->slug ?>"><?= $tag->name ?></option>
												<?php endforeach; ?>
                                            </select>
                                        </td>
                                    </tr>
                                </table>
                            </div>
                        </td>
                    </tr>
				<?php endforeach; ?>
                </tbody>
            </table>
            <p>
                <label for="cronSchedule">Call Every: </label>
                <select name="cronSchedule" required="">
                    <option value=""></option>
                    <option value="1">Only Once</option>
                    <option value="5">Every 5 Minutes</option>
                    <option value="15">Every 15 Minutes</option>
                    <option value="30">Every 30 Minutes</option>
                    <option value="60">Every Hour</option>
                    <option value="180">Every Three Hours</option>
                    <option value="1440">Once a Day</option>
                    <option value="10080">Once a Week</option
                    <option value="43800">Once a Month</option>
                </select>
            </p>
            <p>
                <input type="button" id="cs-back" class="button button-secondary valid" value="Back"/>
                <input type="submit" id="cs-submit" class="button button-primary valid" value="Submit"/>
            </p>
	        <?= wp_nonce_field($block->getPageKey()); ?>
	        <?= $block->getLoaderHtml() ?>
        </form>
	<?php endif; ?>
</div>

<script type="text/javascript" src="<?= EXTERNAL_SERVICES_JS . 'viewObjects/es-configure-service.js' ?>"></script>
<script type="text/javascript">
    jQuery(function ($) {
        let configureService = new EsConfigureService();

        $('#cs-back').click(function () {
            window.history.back();
        });

        $('#configure-service').one('submit', function (event) {
            configureService.checkIfFormIsValid(event, $(this), '<?= $block->getPageKey() ?>');
        });

        // Mass select all mappings boxes
        $('#all-keys').change(function () {
            configureService.massSelectFields($(this));
        });

        $('.data-mappings').change(function () {
            configureService.showOrHideDataSettingsFields(this);
        });

        $('.field-map-select').change(function () {
            configureService.onFieldMapChangeHandle($(this));
        });
    });
</script>