<div id="csvParseForm">
    <p>
        <label for="csv-headers">CSV contain header columns?</label>
        <input type="checkbox" name="csv-headers" value="1" />
    </p>
    <p>
        <label for="csv-delimeter">Deliminate rows by</label>
        <input type="text" name="csv-delimeter" placeholder="Optional, defaults to ','" />
    </p>
    <p>
        <label for="csv-enclosure">Enclose rows character</label>
        <input type="text" name="csv-enclosure" placeholder="Optional, defaults to nothing" />
    </p>
    <p>
        <label for="csv-escape">Escape Character</label>
        <input type="text" name="csv-escape" placeholder="Optional, defaults to '\\'" />
    </p>
</div>