<div id="csvParseForm">
    <p>
        <label for="csv-delimeter">Deliminate rows by</label>
        <input type="text" name="csv-delimeter" placeholder="Optional, defaults to ','" />
    </p>
    <p>
        <label for="csv-enclosure">Enclose rows character</label>
        <input type="text" name="csv-enclosure" placeholder="Optional, defaults to nothing" />
    </p>
    <p>
        <label for="csv-escape">Escape Character</label>
        <input type="text" name="csv-escape" placeholder="Optional, defaults to '\\'" />
    </p>
    <p>
        <label for="csv-columncount">Column Count</label>
        <input type="text" name="csv-columncount" />
        <span class="input-notice">
            Please specify a number to assist with mapping of each data column to a record. Defaults to 1.
        </span>
    </p>
    <p>
        <label for="csv-end-escape">Escape new line at the end of each record?</label>
        <input type="checkbox" name="csv-end-escape" value="1" />
        <span class="input-notice">
            With some CSV's, a new line is populated at the ed of each row of the CSV to indicate that it's the end of a data entity.
            Checking this will correctly map each data column to the correct entity.
        </span>
    </p>
</div>

<script type="text/javascript">
</script>